### ISSUE TITLE
CFG prediction & Perp-neg prediction Nodes - Use Conditioned Prediction?

### ISSUE THREAD

**Issue by dothere** [redhottensors/ComfyUI-Prediction#9]
First of all, thanks for developing these nodes, they're incredibly powerful. I've gotten the best results while using these nodes since you can control so much with them. I was wondering if it would be possible to have the CFG Prediction and Perp-neg Prediction nodes accept predictions as inputs, instead of conditionings. Since the labels of these are fixed to "positive", "negative", and "empty", you can't use more than one of these in the workflow or else it breaks with the error: "Conditioning "positive" is not unique."

**Comment by redhottensors** [comment]
You can actually use whatever names you'd like for the conditioning. They don't have to be "positive", "negative", or "empty" so long as they are unique.

For example, it's perfectly fine to have a conditioning named "asdf" connected to a "baseline" input.

Feel free to re-open if this doesn't actually address your problem.

**Comment by dothere** [comment]
Thanks for the response! Sorry, yeah, let me clarify what I'm trying to do;
As you mentioned, renaming the conditionings/predictions work just fine with any arbitrary amount, as long as they have unique names:
![image](https://github.com/user-attachments/assets/6c6271ca-d1a5-4fbc-b78f-87154d48233a)



However, if trying to do some funky interpolation or combining between Perp-neg/CFG prediction nodes, it errors out:
![image](https://github.com/user-attachments/assets/bfb47667-d383-412c-ae4e-f3aa71af2bfe)
`Traceback (most recent call last):
  File "P:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "P:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Prediction\nodes\nodes_pred.py", line 109, in sample
    samples = sample_pred(
              ^^^^^^^^^^^^
  File "P:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Prediction\nodes\nodes_pred.py", line 147, in sample_pred
    conds = predictor.get_conds()
            ^^^^^^^^^^^^^^^^^^^^^
  File "P:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Prediction\nodes\nodes_pred.py", line 431, in get_conds
    return self.merge_conds(self.lhs, self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Prediction\nodes\nodes_pred.py", line 298, in merge_conds
    elif merged[name] != cond:
         ^^^^^^^^^^^^^^^^^^^^
RuntimeError: Boolean value of Tensor with more than one value is ambiguous`




Or if trying to do prediction switching, like switching between Perp-neg Prediction, then into Characteristic Guidance Prediction, and ending on CFG Prediction:
![image](https://github.com/user-attachments/assets/d8222dd6-36f0-4633-a6a3-f52e8447dc6c)
```
!!! Exception during processing !!! Conditioning "positive" is not unique.
Traceback (most recent call last):
  File "P:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "P:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Prediction\nodes\nodes_pred.py", line 109, in sample
    samples = sample_pred(
              ^^^^^^^^^^^^
  File "P:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Prediction\nodes\nodes_pred.py", line 147, in sample_pred
    conds = predictor.get_conds()
            ^^^^^^^^^^^^^^^^^^^^^
  File "P:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Prediction\nodes\nodes_pred.py", line 540, in get_conds
    return self.merge_conds(self.early_pred, self.middle_pred, self.late_pred)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Prediction\nodes\nodes_pred.py", line 299, in merge_conds
    raise RuntimeError(f"Conditioning \"{name}\" is not unique.")
RuntimeError: Conditioning "positive" is not unique.

```



So it doesn't seem possible to have more than one Perp-neg/CFG Prediction node interacting with each other since you can't change the name of the inputs of those nodes. So if these nodes could be changed to accept Conditioned Prediction, that might resolve the issue.
